package bot

import (
	"fmt"
	"strings"
)

// FormatResultComment builds the GitHub comment body for a successful scan.
func FormatResultComment(owner, repo string, result *ScanResult) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("## archlint scan: `%s/%s`\n\n", owner, repo))

	// Health score bar.
	sb.WriteString(fmt.Sprintf("**Health score:** %d/100 %s\n\n", result.HealthScore, healthBar(result.HealthScore)))

	// Summary line.
	if result.TotalViolations == 0 {
		sb.WriteString("**Status:** PASSED - no violations found\n\n")
	} else {
		sb.WriteString(fmt.Sprintf("**Status:** %d violation(s) found\n\n", result.TotalViolations))
	}

	// Categories breakdown.
	if len(result.Categories) > 0 {
		sb.WriteString("### Violation categories\n\n")
		sb.WriteString("| Category | Count |\n")
		sb.WriteString("|----------|-------|\n")
		for kind, count := range result.Categories {
			sb.WriteString(fmt.Sprintf("| `%s` | %d |\n", kind, count))
		}
		sb.WriteString("\n")
	}

	// Top 5 violations.
	if len(result.TopViolations) > 0 {
		sb.WriteString("### Top violations\n\n")
		for i, v := range result.TopViolations {
			sb.WriteString(fmt.Sprintf("%d. **[%s]** %s", i+1, v.Kind, v.Message))
			if v.Target != "" {
				sb.WriteString(fmt.Sprintf(" (`%s`)", v.Target))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
		if result.TotalViolations > 5 {
			sb.WriteString(fmt.Sprintf("_...and %d more. Run archlint locally for the full report._\n\n",
				result.TotalViolations-5))
		}
	}

	// Add to CI section.
	sb.WriteString("### Add to CI\n\n")
	sb.WriteString("Add archlint quality gate to your GitHub Actions:\n\n")
	sb.WriteString("```yaml\n")
	sb.WriteString(ciYAML(owner, repo))
	sb.WriteString("```\n\n")

	sb.WriteString("---\n")
	sb.WriteString("_Generated by [archlint](https://github.com/mshogin/archlint) scan-by-issue bot._\n")

	return sb.String()
}

// FormatErrorComment builds the GitHub comment body when a scan fails.
func FormatErrorComment(owner, repo string, err error) string {
	return fmt.Sprintf(
		"## archlint scan: `%s/%s`\n\n**Status:** scan failed\n\n```\n%v\n```\n\n---\n_Generated by [archlint](https://github.com/mshogin/archlint) scan-by-issue bot._\n",
		owner, repo, err,
	)
}

// healthBar returns a simple ASCII progress bar for the score.
func healthBar(score int) string {
	filled := score / 10
	empty := 10 - filled
	return "[" + strings.Repeat("█", filled) + strings.Repeat("░", empty) + "]"
}

// ciYAML returns a ready-to-use GitHub Actions workflow snippet.
func ciYAML(_, _ string) string {
	return `name: archlint

on: [push, pull_request]

jobs:
  archlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mshogin/archlint@main
        with:
          args: scan . --threshold 0
`
}
